### ISSUE TITLE
train 大文件训练材料的时候 会coredump

### ISSUE THREAD

**Issue by AutoCoder** [thunlp/THULAC#24]
Program received signal SIGSEGV, Segmentation fault.
_int_realloc (av=av@entry=0x7ffff7830b20 <main_arena>, oldp=oldp@entry=0x1aa9d330, oldsize=oldsize@entry=1451880, nb=nb@entry=1048592) at malloc.c:4262
4262    malloc.c: No such file or directory.
(gdb) bt
#0  _int_realloc (av=av@entry=0x7ffff7830b20 <main_arena>, oldp=oldp@entry=0x1aa9d330, oldsize=oldsize@entry=1451880, nb=nb@entry=1048592) at malloc.c:4262
#1  0x00007ffff74f0839 in __GI___libc_realloc (oldmem=0x1aa9d340, bytes=1048576) at malloc.c:3045
#2  0x000000000041a447 in thulac::DATMaker::extends() ()
#3  0x000000000041a626 in thulac::DATMaker::alloc(std::vector<int, std::allocator<int> >&) ()
#4  0x000000000041a902 in thulac::DATMaker::assign(int, std::vector<int, std::allocator<int> >&, int) ()
#5  0x000000000041aceb in thulac::DATMaker::make_dat(std::vector<thulac::DATMaker::KeyValue, std::allocator<thulac::DATMaker::KeyValue> >&, int) ()
#6  0x00000000004189cd in thulac::TaggingLearner::train(char const*, char const*, char const*, char const*) ()
#7  0x0000000000419970 in main ()

**Comment by AutoCoder** [comment]
我的训练文件大概100M吧

**Comment by alpha19881007** [comment]
设置一下-b 5 参数试试
